version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"

  producer:
    build:
      context: producer
      dockerfile: producer/Dockerfile.development
    container_name: eCab_producer
    image: 'ecab_producer'
    ports:
      - "9000:9000"
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: consumer
      dockerfile: consumer/Dockerfile.development
    container_name: eCab_consumer
    image: 'ecab_consumer'
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq