logging:
  level:
    root: ERROR
    org:
      springframework:
        amqp: debug
    eu.senla.ecabtask: debug
spring:
  application:
    name: consumer-service
  datasource:
    url:   jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      path: /db
      enabled: true

server:
  port: 8000

rabbit:
  addQueue: add
  editQueue: edit
  deleteQueue: delete
  auditQueue: audit