version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  producer:
    build:
      context: producer
      dockerfile: Dockerfile.development
    container_name: eCab_producer
    image: 'ecab_producer'
    ports:
      - "9000:9000"
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: consumer
      dockerfile: Dockerfile.development
    container_name: eCab_consumer
    image: 'ecab_consumer'
    ports:
      - "8000:8000"
    depends_on:
        - rabbitmq